In [1]:
import tensorflow as tf

### Matrix Addition

![Matrix Addition](images/matrix_addition_one.png)

In [2]:
matrix_one = tf.constant([[1, 2], [3, 4]])
matrix_two = tf.constant([[5, 6], [7, 8]])

In [3]:
with tf.Session() as sess:
    print(sess.run(tf.add(matrix_one, matrix_two)))

[[ 6  8]
 [10 12]]


### Broadcasting

![Broadcasting](images/broadcasting_one.png)

In [37]:
matrix_one = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = tf.constant([[10, 11, 12]]) 

In [39]:
with tf.Session() as sess:
    print(sess.run(tf.add(matrix_one, matrix_two)))

[[11 13 15]
 [14 16 18]
 [17 19 21]]


![Broadcasting](images/broadcasting_two.png)

In [41]:
matrix_one = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = tf.constant([[10], [11], [12]]) 

In [42]:
with tf.Session() as sess:
    print(sess.run(tf.add(matrix_one, matrix_two)))

[[11 12 13]
 [15 16 17]
 [19 20 21]]


### Scalar Matrix Multiplication

![Scalar Multiplication](images/scalar_multiplication.png)

In [4]:
multiplier = tf.constant(5)
matrix = tf.constant([[1, 2], [3, 4]])

In [5]:
with tf.Session() as sess:
    print(sess.run(tf.multiply(multiplier, matrix)))

[[ 5 10]
 [15 20]]


In [6]:
with tf.Session() as sess:
    print(sess.run(multiplier * matrix))

[[ 5 10]
 [15 20]]


### Matrix Multiplication
![Matrix Multiplication](images/matrix_multiply_one_correct.png)

In [7]:
matrix_one = tf.constant([[1, 2], [3, 4]])
matrix_two = tf.constant([[5, 6], [7, 8]])

In [8]:
with tf.Session() as sess:
    print(sess.run(tf.matmul(matrix_one, matrix_two)))

[[19 22]
 [43 50]]


In [29]:
## Donot use multiply or * with matrices
with tf.Session() as sess:
    print(sess.run(tf.matmul(matrix_one, matrix_two)))
    print('\nThe following are wrong')
    print(sess.run(matrix_one * matrix_two))
    print(sess.run(tf.multiply(matrix_one, matrix_two)))

[[14]
 [32]
 [50]]

The following are wrong
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


![Matrix Multiplication](images/matrix_multiply_four.png)

In [10]:
matrix_one = tf.constant([[1, 2], [3, 4]])
matrix_two = tf.constant([[5, 6], [7, 8]])

In [11]:
with tf.Session() as sess:
    print(sess.run(tf.matmul(matrix_one, matrix_two)))
    print(sess.run(tf.matmul(matrix_two, matrix_one)))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


![Matrix Multiplication](images/matrix_multiply_two.png)

In [12]:
matrix_one = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
matrix_two = tf.constant([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) 

In [13]:
with tf.Session() as sess:
    print(sess.run(tf.matmul(matrix_one, matrix_two)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


![Matrix Multiplication](images/matrix_multiply_three.png)

In [14]:
matrix_one = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = tf.constant([[1], [2], [3]]) 

In [15]:
with tf.Session() as sess:
    print(sess.run(tf.matmul(matrix_one, matrix_two)))

[[14]
 [32]
 [50]]


### Element wise Multiply
![Broadcasting](images/matrix_multiply_five.png)

In [57]:
matrix_one = tf.constant([[1, 2, 3]])
matrix_two = tf.constant([[2, 2, 2]]) 

In [58]:
with tf.Session() as sess:
    print(sess.run(tf.multiply(matrix_one, matrix_two)))

[[2 4 6]]


### Matrix Transpose
![Matrix Transpose](images/matrix_transpose_one.png)

In [16]:
matrix = tf.constant([[1, 2], [3, 4]])

In [17]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_transpose(matrix)))

[[1 3]
 [2 4]]


![Matrix Transpose](images/matrix_transpose_two.png)

In [18]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])

In [19]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_transpose(matrix)))

[[1 3 5]
 [2 4 6]]


### Matrix Determinant

![Matix Determinant](images/matrix_det.png)

In [48]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [49]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_determinant(matrix)))

-2.0


![Matrix Determinant](images/matrix_det_two.png)

In [22]:
matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

In [23]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_determinant(matrix)))

0.0


### Matrix Inverse

In [24]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [25]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_inverse(matrix)))

[[-2.00000024  1.00000012]
 [ 1.50000012 -0.50000006]]


![Matrix Inverse](images/matrix_inverse_two.png)

In [26]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])
matrix_inverse = tf.matmul(matrix, tf.matrix_inverse(matrix))

In [27]:
with tf.Session() as sess:
    print(sess.run(matrix_inverse))

[[  1.00000000e+00   0.00000000e+00]
 [ -4.76837158e-07   1.00000024e+00]]


### Matrix Diagonal

In [46]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [47]:
with tf.Session() as sess:
    print(sess.run(tf.matrix_diag(matrix)))

[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]

 [[7 0 0]
  [0 8 0]
  [0 0 9]]]


### y = W * x + B

In [54]:
matrix_x = [[.9, .8, .7]]
matrix_weights = [[1.0], [1.0], [1.0]]
bias = 5
with tf.Session() as sess:
    matrix_y = tf.add(tf.matmul(matrix_weights, matrix_x), bias)
    print(sess.run(matrix_y))

[[ 5.9000001   5.80000019  5.69999981]
 [ 5.9000001   5.80000019  5.69999981]
 [ 5.9000001   5.80000019  5.69999981]]
